## Bag of words

In [31]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd
import nltk

In [4]:
doc1='Game of Thrones is an amazing tv series!' 
doc2='Game of Thrones is the best tv series!' 
doc3='Game of Thrones is so great' 

vectorizer=CountVectorizer() 
x=vectorizer.fit_transform([doc1,doc2,doc3]) 
vectorizer.get_feature_names()

C:\Users\Lenovo\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['amazing',
 'an',
 'best',
 'game',
 'great',
 'is',
 'of',
 'series',
 'so',
 'the',
 'thrones',
 'tv']

In [5]:
x.toarray()

array([[1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1],
       [0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0]], dtype=int64)

In [6]:
bow_df=pd.DataFrame(x.toarray(),columns=vectorizer.get_feature_names())
bow_df

   amazing  an  best  game  great  is  of  series  so  the  thrones  tv
0        1   1     0     1      0   1   1       1   0    0        1   1
1        0   0     1     1      0   1   1       1   0    1        1   1
2        0   0     0     1      1   1   1       0   1    0        1   0

In [7]:
#remove stopwords also
vectorizer=CountVectorizer(stop_words='english')
x=vectorizer.fit_transform([doc1,doc2,doc3])
pd.DataFrame(x.toarray(),columns=vectorizer.get_feature_names())

C:\Users\Lenovo\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

   amazing  best  game  great  series  thrones  tv
0        1     0     1      0       1        1   1
1        0     1     1      0       1        1   1
2        0     0     1      1       0        1   0

In [8]:
#using ngrams
vectorizer=CountVectorizer(ngram_range=(2,2))
x=vectorizer.fit_transform([doc1,doc2,doc3])
pd.DataFrame(x.toarray(),columns=vectorizer.get_feature_names())

C:\Users\Lenovo\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,amazing tv,an amazing,best tv,game of,is an,is so,is the,of thrones,so great,the best,thrones is,tv series
0,1,1,0,1,1,0,0,1,0,0,1,1
1,0,0,1,1,0,0,1,1,0,1,1,1
2,0,0,0,1,0,1,0,1,1,0,1,0

## TF-IDF(term frequency-inverse document frequency)

In [10]:
from sklearn.feature_extraction.text import TfidfVectorizer

### example 1

In [12]:
docs=["the house had a tiny little mouse",
      "the cat saw the mouse",
     "the mouse ran away from the house",
     "the cat finally ate the mouse",
     "the end of the mouse story"]

In [13]:
vectorizer=TfidfVectorizer()
sentence_vectors=vectorizer.fit_transform(docs)

In [14]:
vectorizer.get_feature_names_out()

array(['ate', 'away', 'cat', 'end', 'finally', 'from', 'had', 'house',
       'little', 'mouse', 'of', 'ran', 'saw', 'story', 'the', 'tiny'],
      dtype=object)

In [15]:
sentence_vectors.toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.49356209, 0.39820278, 0.49356209, 0.23518498,
        0.        , 0.        , 0.        , 0.        , 0.23518498,
        0.49356209],
       [0.        , 0.        , 0.48334378, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.28547062,
        0.        , 0.        , 0.59909216, 0.        , 0.57094124,
        0.        ],
       [0.        , 0.45709287, 0.        , 0.        , 0.        ,
        0.45709287, 0.        , 0.36877965, 0.        , 0.2178072 ,
        0.        , 0.45709287, 0.        , 0.        , 0.43561441,
        0.        ],
       [0.51392301, 0.        , 0.41462985, 0.        , 0.51392301,
        0.        , 0.        , 0.        , 0.        , 0.24488707,
        0.        , 0.        , 0.        , 0.        , 0.48977413,
        0.        ],
       [0.        , 0.        , 0.        , 0.49175319, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.23432303,
        0.49175319, 0.        , 0.        , 0.49175319, 0.46864606,
        0.        ]])

In [19]:
#get the first vector out(for the first sentence)
first_vector=sentence_vectors[0]
#place tf-idf values in a pandas data frame
df=pd.DataFrame(first_vector.T.toarray(),index=vectorizer.get_feature_names_out(),columns=["tfidf"])
df.sort_values(by=["tfidf"],ascending=False)

            tfidf
had      0.493562
little   0.493562
tiny     0.493562
house    0.398203
mouse    0.235185
the      0.235185
ate      0.000000
away     0.000000
cat      0.000000
end      0.000000
finally  0.000000
from     0.000000
of       0.000000
ran      0.000000
saw      0.000000
story    0.000000

In [22]:
pd.DataFrame(sentence_vectors.toarray(),columns=vectorizer.get_feature_names_out())

,ate,away,cat,end,finally,from,had,house,little,mouse,of,ran,saw,story,the,tiny
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.493562,0.398203,0.493562,0.235185,0.000000,0.000000,0.000000,0.000000,0.235185,0.493562
1,0.000000,0.000000,0.483344,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.285471,0.000000,0.000000,0.599092,0.000000,0.570941,0.000000
2,0.000000,0.457093,0.000000,0.000000,0.000000,0.457093,0.000000,0.368780,0.000000,0.217807,0.000000,0.457093,0.000000,0.000000,0.435614,0.000000
3,0.513923,0.000000,0.414630,0.000000,0.513923,0.000000,0.000000,0.000000,0.000000,0.244887,0.000000,0.000000,0.000000,0.000000,0.489774,0.000000
4,0.000000,0.000000,0.000000,0.491753,0.000000,0.000000,0.000000,0.000000,0.000000,0.234323,0.491753,0.000000,0.000000,0.491753,0.468646,0.000000

##  Word2Vec

In [27]:
pip install gensim

Collecting gensim
  Downloading gensim-4.2.0-cp39-cp39-win_amd64.whl (23.9 MB)
Collecting smart-open>=1.8.1
  Downloading smart_open-6.2.0-py3-none-any.whl (58 kB)
Requirement already satisfied: numpy>=1.17.0 in c:\users\lenovo\anaconda3\lib\site-packages (from gensim) (1.20.3)
Collecting Cython==0.29.28
  Downloading Cython-0.29.28-py2.py3-none-any.whl (983 kB)
Requirement already satisfied: scipy>=0.18.1 in c:\users\lenovo\anaconda3\lib\site-packages (from gensim) (1.7.1)
Installing collected packages: smart-open, Cython, gensim
  Attempting uninstall: Cython
    Found existing installation: Cython 0.29.24
    Uninstalling Cython-0.29.24:
      Successfully uninstalled Cython-0.29.24
Successfully installed Cython-0.29.28 gensim-4.2.0 smart-open-6.2.0
Note: you may need to restart the kernel to use updated packages.

In [28]:
import gensim
from gensim.models import Word2Vec
from nltk.corpus import brown,movie_reviews,treebank

In [32]:
#nltk.download('brown')

[nltk_data] Downloading package brown to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\brown.zip.

True

In [35]:
#nltk.download('movie_reviews')

[nltk_data] Downloading package movie_reviews to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\movie_reviews.zip.

True

In [36]:
#nltk.download('treebank')

[nltk_data] Downloading package treebank to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\treebank.zip.

True

In [39]:
brown_corpus=Word2Vec(brown.sents()).wv
movie_review_corpus=Word2Vec(movie_reviews.sents()).wv
tree_corpus=Word2Vec(treebank.sents()).wv

In [43]:
tree_corpus.index_to_key  #get the vocabulary

[',',
 'the',
 '.',
 'of',
 'to',
 'a',
 'in',
 'and',
 '*-1',
 '0',
 '*',
 "'s",
 'for',
 'that',
 '*T*-1',
 '*U*',
 '$',
 'The',
 '``',
 "''",
 'is',
 'said',
 'on',
 'it',
 '%',
 'by',
 'at',
 'with',
 'from',
 'as',
 'million',
 'Mr.',
 '*-2',
 'are',
 'was',
 'be',
 '*T*-2',
 'has',
 'its',
 "n't",
 'have',
 'an',
 'or',
 'will',
 'company',
 'he',
 '--',
 'which',
 'U.S.',
 'year',
 'they',
 'says',
 'would',
 'about',
 'more',
 'In',
 'were',
 'this',
 'their',
 'than',
 'market',
 ';',
 'New',
 'had',
 'who',
 'trading',
 'new',
 'billion',
 'But',
 'up',
 'but',
 'been',
 'also',
 ':',
 'stock',
 'other',
 'not',
 'president',
 'one',
 '*-3',
 'program',
 'some',
 'his',
 'could',
 'share',
 'because',
 'Corp.',
 'years',
 'I',
 'shares',
 '-RRB-',
 'A',
 'York',
 '-LRB-',
 'any',
 'two',
 'all',
 'It',
 '*T*-3',
 'Inc.',
 'can',
 'Japanese',
 'last',
 'no',
 'such',
 'into',
 'prices',
 '&',
 'do',
 'government',
 'many',
 'over',
 'if',
 'only',
 'out',
 'after',
 'she',
 'when',
 'business',
 'Japan',
 'say',
 'most',
 'first',
 'Co.',
 'make',
 'He',
 "'",
 'recent',
 'so',
 'you',
 'them',
 '*ICH*-1',
 'cents',
 'may',
 'even',
 'executive',
 'there',
 'American',
 'next',
 'stocks',
 'funds',
 'price',
 'index',
 'futures',
 'time',
 'companies',
 'investors',
 'did',
 'October',
 'now',
 'rose',
 'yesterday',
 'issue',
 'under',
 'much',
 'bonds',
 'months',
 'sales',
 'profit',
 'Mrs.',
 'common',
 'like',
 'investment',
 'made',
 'yen',
 'people',
 'down',
 'House',
 'these',
 'those',
 'week',
 'does',
 'interest',
 'buy',
 'markets',
 'They',
 'money',
 'what',
 'expected',
 'net',
 'days',
 '10',
 'chief',
 'banks',
 'federal',
 'her',
 'since',
 'Exchange',
 'trade',
 'rates',
 'own',
 'higher',
 'while',
 'three',
 'we',
 'take',
 'yield',
 'before',
 'earlier',
 'traders',
 'plan',
 'officials',
 'get',
 'offer',
 'We',
 '30',
 'country',
 'Tuesday',
 '50',
 'Congress',
 'well',
 'debt',
 'sell',
 'number',
 'off',
 '1988',
 'chairman',
 '*?*',
 'small',
 'just',
 'Bush',
 'vice',
 'might',
 'major',
 'Department',
 'And',
 'month',
 'cash',
 'help',
 'Chicago',
 '1',
 'Board',
 'group',
 'early',
 '1990',
 'fiscal',
 'good',
 'income',
 '15',
 'concern',
 'rate',
 'another',
 'financial',
 'September',
 'through',
 'industry',
 'Treasury',
 'economic',
 'pay',
 '?',
 'firm',
 '100',
 'If',
 'report',
 '1989',
 'South',
 'That',
 'added',
 'This',
 'less',
 'managers',
 'spokesman',
 'growth',
 'due',
 'part',
 'including',
 'sold',
 'investor',
 '500',
 'during',
 'First',
 'Street',
 'earnings',
 'should',
 'bank',
 'ago',
 'use',
 'Columbia',
 'same',
 'Yeargin',
 'contract',
 'law',
 'big',
 'Wall',
 'each',
 'reported',
 'Cray',
 'unit',
 '8',
 'Stock',
 'For',
 'quarter',
 'test',
 'still',
 'between',
 'bid',
 'issues',
 'already',
 'both',
 'Big',
 'court',
 'S&P',
 'where',
 '*ICH*-2',
 'against',
 '*RNR*-1',
 'right',
 'John',
 'firms',
 'plans',
 'according',
 '*-4',
 '*EXP*-1',
 'being',
 'securities',
 'research',
 'International',
 'bill',
 'few',
 'compared',
 'below',
 'current',
 'far',
 '1987',
 'director',
 'loss',
 'capital',
 'used',
 'average',
 'began',
 'Bank',
 'notes',
 'several',
 'officer',
 'fell',
 'products',
 'There',
 'state',
 'increase',
 'lower',
 'six',
 'construction',
 'until',
 'points',
 'based',
 'students',
 'among',
 'high',
 'very',
 'closed',
 'charge',
 'administration',
 'problem',
 'around',
 'way',
 'record',
 'board',
 'As',
 'analysts',
 '2',
 'end',
 'junk',
 'large',
 'demand',
 'past',
 'want',
 'case',
 'public',
 "'re",
 'set',
 'though',
 'see',
 'orders',
 'point',
 'operations',
 'five',
 'without',
 'problems',
 '3\\/4',
 'maker',
 'ad',
 'took',
 'cut',
 'President',
 'paper',
 'return',
 'At',
 'whether',
 'largest',
 'manager',
 'Campbell',
 'department',
 'analyst',
 'example',
 'work',
 'close',
 'Securities',
 'action',
 '1\\/2',
 'sale',
 'then',
 'us',
 'Group',
 '13',
 'priced',
 'long',
 'members',
 'our',
 'additional',
 'future',
 'costs',
 'bond',
 'London',
 'California',
 'spending',
 'move',
 'information',
 'economy',
 'operating',
 'certain',
 'offered',
 'suspension',
 'approved',
 'noted',
 'power',
 'nation',
 'Oct.',
 'services',
 'fine',
 'corporate',
 'low',
 'purchase',
 'period',
 'back',
 'how',
 'While',
 '20',
 'come',
 'offering',
 'appropriations',
 'China',
 'recently',
 'result',
 'service',
 'old',
 'division',
 'least',
 'ended',
 'however',
 'possible',
 'total',
 'value',
 'Some',
 'Robert',
 'You',
 'strong',
 'often',
 'Tokyo',
 'news',
 'contracts',
 'little',
 'fall',
 'Nov.',
 'commercial',
 '40',
 'stake',
 'addition',
 'William',
 'your',
 'face',
 'programs',
 'foreign',
 'USX',
 'office',
 '*T*-4',
 'think',
 'force',
 'Washington',
 'day',
 '12',
 'customers',
 'sugar',
 'safety',
 'Georgia',
 'dividend',
 'become',
 'England',
 'half',
 'veto',
 'found',
 'growing',
 'magazine',
 'increased',
 'local',
 'computer',
 'too',
 'manufacturing',
 'University',
 'latest',
 'gains',
 'proposed',
 'weeks',
 'support',
 'card',
 'change',
 'James',
 'declined',
 'trying',
 'So',
 'received',
 'These',
 'likely',
 'school',
 'cases',
 'legislation',
 'II',
 'go',
 'currently',
 'world',
 'management',
 'named',
 'questions',
 'today',
 'put',
 'arbitrage',
 'almost',
 'production',
 'Association',
 'Research',
 'Union',
 'plant',
 'exchange',
 'ringers',
 'decline',
 'payments',
 'volatility',
 'outstanding',
 'give',
 'trades',
 'held',
 'volume',
 'takeover',
 'High',
 'limit',
 'countries',
 'full',
 '15,000',
 'different',
 'When',
 'One',
 'She',
 'results',
 'America',
 'raise',
 'came',
 'family',
 'never',
 'dividends',
 'rise',
 'proposal',
 'transactions',
 'Edison',
 'level',
 'product',
 'credit',
 'general',
 'Federal',
 'Hahn',
 'designed',
 'called',
 'paid',
 '3',
 'estimated',
 '7',
 'transaction',
 'holding',
 'shareholders',
 'continue',
 'private',
 'official',
 'rights',
 'workers',
 'four',
 'Gulf',
 'going',
 'making',
 'Rep.',
 'employees',
 'deal',
 'talks',
 'National',
 'Jones',
 'Dow',
 'senior',
 'here',
 'funding',
 'decision',
 'better',
 'comment',
 'Korea',
 'What',
 'Ltd.',
 'Express',
 'restructuring',
 'drop',
 'United',
 'fees',
 'Soviet',
 'stock-index',
 'political',
 'lead',
 'seeking',
 'cars',
 'gain',
 'banking',
 'bells',
 '5',
 'place',
 'amount',
 'Sales',
 'Inc',
 'must',
 'San',
 'former',
 'every',
 'bills',
 'corn',
 'wo',
 'health',
 'executives',
 'expects',
 'previous',
 'enough',
 'pressure',
 'development',
 'run',
 'real',
 'increasing',
 'above',
 'home',
 'conditions',
 'order',
 '18',
 'Buick',
 'August',
 'my',
 'international',
 'institutions',
 'effect',
 '9',
 'thrift',
 '1991',
 'finance',
 'A.',
 'An',
 'Senate',
 'performance',
 'Industries',
 'March',
 'insurance',
 'job',
 'got',
 'Nixon',
 'industrial',
 'buying',
 'clients',
 'acquired',
 'terms',
 'saying',
 'owns',
 'oil',
 'need',
 'gained',
 '10,000',
 'fined',
 'wage',
 'important',
 'survey',
 'composite',
 '11',
 'announced',
 'Commerce',
 'equity',
 'agency',
 'Boston',
 'sector',
 'Many',
 'filed',
 'included',
 'Dec.',
 'tax',
 'charges',
 'control',
 'team',
 'To',
 '6',
 'late',
 '1985',
 'Michael',
 'wine',
 'dollars',
 'further',
 'away',
 'assets',
 'annual',
 'became',
 'White',
 'agreed',
 'system',
 'form',
 'investments',
 'On',
 'marketing',
 'nearly',
 'seek',
 'agreement',
 'reached',
 'city',
 'package',
 'particularly',
 'clear',
 'using',
 'tests',
 'failed',
 'region',
 'cost',
 'Containers',
 'meeting',
 'Moody',
 'able',
 'delivery',
 'farmers',
 'Sea',
 'Commission',
 'following',
 'know',
 'yet',
 'food',
 '31',
 'principal',
 'Also',
 'Co',
 'coming',
 'decided',
 'Texas',
 'led',
 'dollar',
 'loan',
 'rather',
 'Financial',
 'Wednesday',
 'R.',
 'light',
 'UAL',
 'disclosed',
 'keep',
 'find',
 'violations',
 'increases',
 'times',
 '4',
 '...',
 'Calif.',
 'materials',
 'Ford',
 '#',
 'City',
 'him',
 'taken',
 'changes',
 'Shearson',
 'car',
 'activity',
 "'ve",
 'completed',
 'raised',
 'Institute',
 'campaign',
 'D.',
 'fact',
 'across',
 'women',
 'computers',
 'Hills',
 'lost',
 '3\\/8',
 'Mitsubishi',
 'nations',
 'potential',
 'acquisition',
 'NL',
 'needed',
 'dealers',
 'buy-out',
 'built',
 'trucks',
 'statement',
 'J.',
 'via',
 'always',
 'budget',
 'Asia',
 '17',
 'free',
 'St.',
 'third',
 'traded',
 'things',
 'School',
 'special',
 'World',
 'grain',
 'wines',
 'Judge',
 'Phelan',
 'policy',
 'reports',
 'closely',
 'provide',
 'U.K.',
 'building',
 'told',
 'helped',
 'holders',
 'December',
 'others',
 'apparently',
 'posted',
 'available',
 'June',
 'purchasing',
 'probably',
 'include',
 'Under',
 'General',
 'once',
 'rule',
 'working',
 'scheduled',
 'Last',
 'Commonwealth',
 'Trade',
 'regulators',
 'look',
 'minimum',
 'second',
 'Thomas',
 'State',
 'Ms.',
 'All',
 'bad',
 'software',
 'matter',
 'goes',
 'huge',
 'question',
 'Francisco',
 'life',
 'wants',
 'line',
 'rating',
 'jobs',
 'lawyers',
 '-LCB-',
 'data',
 'Although',
 'went',
 'Johnson',
 'review',
 'personal',
 'short-term',
 'cause',
 'thing',
 'paying',
 'again',
 'Voice',
 'kind',
 'aid',
 'capacity',
 'whose',
 'David',
 'continued',
 'despite',
 'believe',
 '-RCB-',
 'long-term',
 'significant',
 'IRS',
 'receive',
 'indicated',
 'planned',
 'committee',
 'continuing',
 'launched',
 'short',
 'April',
 'convertible',
 'slow',
 'PLC',
 'Sony',
 'person',
 'consumer',
 'process',
 'Los',
 'fund',
 'within',
 'Wedtech',
 'newspaper',
 'strike',
 'export',
 'ordered',
 'evidence',
 '25',
 'publishing',
 'continues',
 'changed',
 'something',
 'Richard',
 'airline',
 'although',
 'dropped',
 '5\\/8',
 'Program',
 'Fujitsu',
 'preferred',
 '7\\/8',
 'Carolina',
 'quickly',
 'third-quarter',
 'Greenville',
 'pretax',
 'losses',
 'position',
 'caused',
 'Hearst',
 'auto',
 'advertisers',
 '90',
 'levels',
 'Ward',
 'known',
 'Western',
 'antitrust',
 "'m",
 '*ICH*-3',
 '60',
 'Herald',
 'West',
 'study',
 'researchers',
 'teacher',
 'remains',
 'Among',
 'departure',
 'showed',
 'Dr.',
 'Drexel',
 'gives',
 '70',
 'leading',
 'financing',
 'concerns',
 'profits',
 'Scoring',
 'individual',
 'savings',
 'generally',
 'reduce',
 'states',
 'Sept.',
 'Justice',
 'drug',
 'abortion',
 'advertising',
 'wanted',
 'show',
 'later',
 'situation',
 'Computer',
 'alleged',
 'pence',
 'domestic',
 'goods',
 'fully',
 'traditional',
 'Management',
 'head',
 'May',
 'crash',
 'slowing',
 'steel',
 '14',
 'Court',
 'improve',
 'subject',
 'includes',
 'defense',
 'legal',
 'McGovern',
 'themselves',
 ...]

In [41]:
movie_review_corpus.most_similar('good',topn=5)

[('bad', 0.850131094455719),
 ('nice', 0.7763107419013977),
 ('great', 0.7724884152412415),
 ('funny', 0.7624520659446716),
 ('perfect', 0.7091996669769287)]

In [42]:
brown_corpus.most_similar('political',topn=5)

[('military', 0.9455099105834961),
 ('economic', 0.9435995817184448),
 ('social', 0.9387313723564148),
 ('individual', 0.9212629795074463),
 ('religious', 0.9194707870483398)]

In [44]:
tree_corpus.most_similar('largest',topn=5)

[('business', 0.9992899298667908),
 ('Corp.', 0.9992743730545044),
 ('A', 0.9992663264274597),
 ('an', 0.9991934299468994),
 ('while', 0.9991920590400696)]